### ISSUE TITLE
Hard/Easy Mode Enabled By Default

### ISSUE THREAD

**Issue by XerShade** [Karanum/gs2-randomiser2#27]
If possible can we patch the game so it asks for Hard or Easy mode without having to beat the game first? Would make starting a hard or easy mode run less tedious porting a save from a vanilla or other seed into the new seed each time.

**Comment by Karanum** [comment]
Adding a setting in the next version that automatically enables Hard Mode when starting a new game. Decided not to add anything for Easy Mode because it requires a cleared save to transfer stuff anyway.
